# Generated by Django 4.0.4 on 2022-06-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nota_fiscal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota_fiscal',
            old_name='cnpj',
            new_name='CNPJ',
        ),
        migrations.RenameField(
            model_name='nota_fiscal',
            old_name='descricao',
            new_name='Descrição',
        ),
        migrations.RenameField(
            model_name='nota_fiscal',
            old_name='numero',
            new_name='Numero',
        ),
        migrations.RenameField(
            model_name='nota_fiscal',
            old_name='valor',
            new_name='Valor',
        ),
        migrations.RenameField(
            model_name='nota_fiscal',
            old_name='vendedor',
            new_name='Vendedor',
        ),
    ]
