# Generated by Django 4.0.4 on 2022-06-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cpf',
            new_name='CPF',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='endereco',
            new_name='Endereço',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='Nome',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='telefone',
            new_name='Telefone',
        ),
    ]
