# Generated by Django 4.0.4 on 2022-06-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
            ],
        ),
    ]
