# Generated by Django 4.0.4 on 2022-06-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='codigo',
            new_name='Código',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='marca',
            new_name='Marca',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='peso',
            new_name='Peso',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='valor',
            new_name='Valor',
        ),
    ]
